# Generated by Django 3.0 on 2023-12-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20231221_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Registered', '已挂号'), ('Cancelled', '已取消'), ('Processing', '就诊中'), ('Finished', '就诊结束')], max_length=10, verbose_name='状态'),
        ),
    ]
