# Generated by Django 3.0 on 2023-12-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20231221_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='room_number',
            field=models.CharField(default='a101', max_length=20, verbose_name='房间号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.CharField(default='', max_length=200, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
