# Generated by Django 3.0 on 2023-12-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已挂号'), (1, '已取消'), (2, '就诊中'), (3, '就诊结束')], max_length=10, verbose_name='状态'),
        ),
    ]
