# Generated by Django 3.0 on 2023-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20231227_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('type', models.SmallIntegerField(choices=[(0, '中药'), (1, '西药')], verbose_name='类型')),
                ('producer', models.CharField(max_length=30, verbose_name='生产厂商')),
                ('price', models.IntegerField(verbose_name='价格')),
            ],
        ),
    ]
