# Generated by Django 3.0 on 2023-12-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='producer',
            field=models.CharField(max_length=100, verbose_name='生产厂商'),
        ),
    ]
