# Generated by Django 3.0 on 2023-12-29 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20231229_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.CharField(max_length=2000, verbose_name='诊断结果'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='solution',
            field=models.CharField(max_length=2000, verbose_name='治疗方案'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='symptom',
            field=models.CharField(max_length=2000, verbose_name='症状'),
        ),
    ]
